export const allProjects = [
  {
    id: 1,
    title: "Project One",
    description: "Project Description for Project One",
    goal: 150,
    image: "https://via.placeholder.com/300.jpg",
    is_open: false,
    date_created: "2020-03-20T14:28:23.382748Z",
    owner: "bronwyn",
    shelter: "Greyhound Rescue",
    is_approved: true,
    species: ["Cat"],
  },
  {
    id: 3,
    title: "Project Two",
    description: "Project Description for Project Two",
    goal: 150,
    image: "https://via.placeholder.com/300.jpg",
    is_open: false,
    date_created: "2020-03-20T14:28:23.382748Z",
    owner: "bronwyn",
    shelter: "Greyhound Rescue",
    is_approved: true,
    species: ["Cat"],
  },
  {
    id: 4,
    title: "Project Three",
    description: "Project Description for Project Three",
    goal: 150,
    image: "https://via.placeholder.com/300.jpg",
    is_open: false,
    date_created: "2020-03-20T14:28:23.382748Z",
    owner: "bronwyn",
    shelter: "Greyhound Rescue",
    is_approved: true,
    species: ["Cat"],
  },
  {
    id: 5,
    title: "Project Four",
    description: "Project Description for Project Four",
    goal: 150,
    image: "https://via.placeholder.com/300.jpg",
    is_open: false,
    date_created: "2020-03-20T14:28:23.382748Z",
    owner: "bronwyn",
    shelter: "Greyhound Rescue",
    is_approved: true,
    species: ["Cat"],
  },
  {
    id: 6,
    title: "Project Five",
    description: "Project Description for Project Five",
    goal: 150,
    image: "https://via.placeholder.com/300.jpg",
    is_open: false,
    date_created: "2020-03-20T14:28:23.382748Z",
    owner: "bronwyn",
    shelter: "Greyhound Rescue",
    is_approved: true,
    species: ["Dog"],
  },
];

export const oneProject = {
  id: 1,
  title: "Project One",
  description: "Project Description for Project One",
  goal: 150,
  image: "https://via.placeholder.com/300.jpg",
  is_open: false,
  date_created: "2020-03-20T14:28:23.382748Z",
  owner: "bronwyn",
  shelter: "Greyhound Rescue",
  is_approved: true,
  species: ["Cat"],
  pledges: [
    {
      id: 1,
      amount: 50,
      comment: "Love this project!",
      anonymous: false,
      supporter: "bronwyn",
      project_id: 1,
    },
  ],
};
